import os
import sys

print("=" * 60)
print("YOLOv8n模型下载指南")
print("=" * 60)
print()
print("由于网络限制，请按以下步骤手动下载模型文件：")
print()
print("步骤1: 从以下任一地址下载 yolov8n.pt (约6MB)")
print()
print("  方案A - 官方GitHub (需要科学上网)")
print("  https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt")
print()
print("  方案B - Hugging Face镜像")
print("  https://hf-mirror.com/Ultralytics/YOLOv8/resolve/main/yolov8n.pt")
print()
print("  方案C - 百度网盘 (如果可用)")
print("  链接: https://pan.baidu.com/s/1b-hrRL3aD9tZ2D2iN7yA8w")
print("  提取码: yolo")
print()
print("步骤2: 将下载的 yolov8n.pt 文件保存到:")
print(f"  {os.getcwd()}")
print()
print("步骤3: 运行程序")
print("  python main.py")
print()
print("=" * 60)
print()
input("按回车键退出...")
